apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: repository
    path: demo/applicationa
    targetRevision: HEAD
  destination: 
    name: in-cluster
    namespace: default
